repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml      # Verifies YAML syntax
      - id: check-json      # Verifies JSON syntax
      - id: end-of-file-fixer # Ensures files end with a newline
      - id: trailing-whitespace # Trims trailing spaces

  - repo: local
    hooks:
      - id: sigma-cli
        name: sigma-cli validate/convert
        language: system
        entry: sigma
        # Pass desired sigma-cli arguments here, e.g., check/convert rules
        args: ["check"] 
        files: '\.yml$'
